<?php
namespace frontend\models;
use yii\db\ActiveRecord;

/**
 * Created by PhpStorm.
 * User: hasee
 * Date: 2017/6/20
 * Time: 23:27
 */
class Locations extends ActiveRecord{
    public function rules()
    {
        return [
            ['name','safe'],
        ];
    }
    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}