<?php
namespace frontend\widgets;

use frontend\models\Goods_Category;
use yii\base\Widget;
//商品分类缓存
class CategoryWidgets extends Widget{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        //检测redis是否有商品分类缓存
//        $redis = new \Redis();
//        $redis->connect();
//        $category_html = $redis->get('category_html');
//        if($category_html==null){
        $category = Goods_Category::findAll(['parent_id'=>0]);//一级分类
        $category_html = $this->renderFile('@app/widgets/view/category.php',['category'=>$category]);
        return$category_html;

/*
        parent::run(); // TODO: Change the autogenerated stub*/
    }
}