<?php
namespace backend\components;


use Codeception\Lib\Generator\Helper;
use yii\base\ActionFilter;
use yii\grid\ActionColumn;
use yii\web\HttpException;

class RbacFilter extends ActionFilter{

    //拦截用户，如果没权限，抛出403异常
    public function beforeAction($action)
    {
        //创建用户对象
        $user = \Yii::$app->user;
        if (!$user->can($action->uniqueId)) {
            //判断用户是否登录
            if ($user->isGuest) {
                return $action->controller->redirect($user->loginUrl);
            }
            throw new HttpException(403, '对不起，你没有该权限');
            return false;
        }

 /*       //删除
        if (\Yii::$app->user->can($action->uniqueId, ['id' => $user->id])) {
            return true;
         }else{
            return false;
        }*/
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }


}